name: Build

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Lighthouse Test
        run: make lighthouse-test || true

      - name: Copy test results
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: pixboost
          APPLICATION_CREDENTIALS: ${{ secrets.gcp_credentials }}
        with:
          args: cp -r ./.lighthouseci/* gs://pixboost-www/.lighthouse-ci/run-777/
          cli: gsutil
      - name: Copy web site
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: pixboost
          APPLICATION_CREDENTIALS: ${{ secrets.gcp_credentials }}
        with:
          args: cp -r ./site/public/* gs://pixboost-www/
          cli: gsutil
